name: Build and Push Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: nodejs-hello-world
  RESOURCE_GROUP_NAME: devops-rg
  NSG_NAME: sonarqube-nsg
  NSG_RULE_NAME: AllowGitHubRunner-${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Azure Login
        id: azlogin
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'

      - name: Allow Azure Connectivity from GitHub Runner
        id: allowconnectivity
        run: |
          RUNNER_IP=$(curl http://api.ipify.org)
          az network nsg rule create --name ${NSG_RULE_NAME} --nsg-name ${NSG_NAME} --priority 100 --resource-group ${RESOURCE_GROUP_NAME} --access Allow --destination-port-ranges 8080 --direction Inbound --protocol Tcp --source-address-prefixes ${RUNNER_IP}/32 -o tsv
          sleep 120
   
      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Run SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         
      - name: Disable Azure Connectivity from GitHub Runner
        if: ${{ steps.allowconnectivity.conclusion == 'success' }}
        run: |
          # Check if NSG exists before attempting to delete the NSG rule
          nsg_exists=$(az network nsg show --name $NSG_NAME --resource-group $RESOURCE_GROUP_NAME --query "name" --output tsv 2>/dev/null)
          
          if [[ -z $nsg_exists ]]; then
            echo "NSG $NSG_NAME does not exist."
          else
            echo "NSG $NSG_NAME exists. Attempting to delete NSG rule $NSG_RULE_NAME..."
            
            # Delete NSG rule
            az network nsg rule delete --name $NSG_RULE_NAME --nsg-name $NSG_NAME --resource-group $RESOURCE_GROUP_NAME
            
            echo "NSG rule $NSG_RULE_NAME has been deleted from NSG $NSG_NAME."
          fi
      
      - name: Azure Logout
        if: ${{ steps.azlogin.conclusion == 'success' }}
        run: |
          az logout
          az cache purge
          az account clear

      - name: Login to Docker Hub
        if: ${{ false }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        if: ${{ false }}
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag Docker image
        if: ${{ false }}
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.run_id }}
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Push Docker image
        if: ${{ false }}
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
